/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package xdhacks;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.util.Scanner;



public class frame extends javax.swing.JFrame {
   
    int carCount1=0;
    int busCount1=0;
    int carCount2=0;
    int busCount2=0;
    boolean running=false;
   
    public frame() {
        initComponents();
        
        
    }
   
    public void loadData() {
        
        //ability to reference text file no matter where program is stored(relative path)
        String currentDirectory = System.getProperty("user.dir");
        String fullFileName = currentDirectory + "\\src\\xdhacks\\traffic.txt";
      
        
        try {   
                FileReader fr = new FileReader(fullFileName);
                BufferedReader br = new BufferedReader(fr);
                String line="";
                carCount1=Integer.parseInt(br.readLine());
                busCount1=Integer.parseInt(br.readLine());
                br.close();
        }
            catch(Exception e) {
                System.out.println("Something went wrong file reading!");
        }
    }
    
    public void writeData(int result){
        
        
        String currentDirectory = System.getProperty("user.dir");
        String fullFileName = currentDirectory + "\\src\\xdhacks\\results.txt";
        
        try {
            FileWriter fw = new FileWriter(fullFileName);
            fw.flush();
            BufferedWriter br = new BufferedWriter(fw);
            br.write("" + result);        //add a newline character
           
            br.close();
            
        }
        catch(Exception e) {
            System.out.println("Error writing to file");
        }
    }
    
    public void Return(){
        
        double val1=(double)carCount1+(busCount1*1.1);
        double val2=(double)carCount2+(busCount2*1.1);
        if((val1>val2)&&(busCount1>0||busCount2>0)){
            textResult.setText("Lane 1 may pass!");
            this.writeData(1);
                           
        }else if((val1<val2)&&(busCount1>0||busCount2>0)){
            textResult.setText("Lane 2 may pass!");
            this.writeData(2);
        }
        else{
            textResult.setText("Proceed per usual");
            this.writeData(0);
        }
        
    }
   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textCar1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textBus1 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        textCar2 = new javax.swing.JTextField();
        textBus2 = new javax.swing.JTextField();
        buttonStart = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        textResult = new javax.swing.JTextField();
        boxMode = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 255));

        jLabel1.setText("Lane #1:");

        jLabel2.setText("Lane #2:");

        jLabel3.setText("Car count:");

        textCar1.setText("0");
        textCar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCar1ActionPerformed(evt);
            }
        });

        jLabel4.setText("Truck/Bus count:");

        textBus1.setText("0");
        textBus1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBus1ActionPerformed(evt);
            }
        });

        jLabel5.setText("Car count:");

        jLabel6.setText("Truck/Bus count:");

        textCar2.setText("0");
        textCar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textCar2ActionPerformed(evt);
            }
        });

        textBus2.setText("0");
        textBus2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textBus2ActionPerformed(evt);
            }
        });

        buttonStart.setText("Start");
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });

        jLabel7.setText("Result:");

        boxMode.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Auto",}));
        boxMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxModeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textBus1, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                    .addComponent(textCar1)))
                            .addComponent(textResult))
                        .addGap(98, 98, 98)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(textBus2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(boxMode, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(buttonStart, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(textCar2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 35, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel5))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textCar2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textCar1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textBus1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(textBus2, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxMode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonStart))
                .addGap(55, 55, 55))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textCar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCar1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCar1ActionPerformed

    private void textCar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textCar2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textCar2ActionPerformed

    private void textBus2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBus2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBus2ActionPerformed

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed
      
        if(boxMode.getSelectedItem().equals("Manual")){
            if(running==false){
       
                carCount1 = Integer.parseInt(textCar1.getText());
                carCount2 = Integer.parseInt(textCar2.getText());
       
                busCount1 = Integer.parseInt(textBus1.getText());
                busCount2 = Integer.parseInt(textBus2.getText());
                
                textCar1.setEnabled(false);
                textCar2.setEnabled(false);
                textBus1.setEnabled(false);
                textBus2.setEnabled(false);
               
                Return();
                
                running=true;
                buttonStart.setText("Restart");
            } else {
                textCar1.setText("0");
                textCar2.setText("0");
                textBus1.setText("0");
                textBus2.setText("0");
                
                carCount1 = 0;
                carCount2 = 0;
                busCount1 = 0;
                busCount2 = 0;
                textCar1.setEnabled(true);
                textCar2.setEnabled(true);
                textBus1.setEnabled(true);
                textBus2.setEnabled(true);
                running=false;
                buttonStart.setText("Start");
            }
        } else if(boxMode.getSelectedItem().equals("Auto")){
          
            if(running==false){
                loadData();
                carCount2 = Integer.parseInt(textCar2.getText());
                busCount2 = Integer.parseInt(textBus2.getText());
       
                textCar1.setEnabled(false);
                textCar2.setEnabled(false);
                textBus1.setEnabled(false);
                textBus2.setEnabled(false);
                Return();
                running=true;
                buttonStart.setText("Restart");
                
            } else {
                textCar1.setText("0");
                textCar2.setText("0");
                textBus1.setText("0");
                textBus2.setText("0");
                carCount1 = 0;
                carCount2 = 0;
                busCount1 = 0;
                busCount2 = 0;
                textCar1.setEnabled(true);
                textCar2.setEnabled(true);
                textBus1.setEnabled(true);
                textBus2.setEnabled(true);
                running=false;
                buttonStart.setText("Start");
            }   
        }  
    }//GEN-LAST:event_buttonStartActionPerformed

    private void textBus1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textBus1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textBus1ActionPerformed

    private void boxModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxModeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxModeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])  {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxMode;
    private javax.swing.JButton buttonStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField textBus1;
    private javax.swing.JTextField textBus2;
    private javax.swing.JTextField textCar1;
    private javax.swing.JTextField textCar2;
    private javax.swing.JTextField textResult;
    // End of variables declaration//GEN-END:variables
}
